### ISSUE TITLE
Block rigidbody doesn't react properly with arrows

### ISSUE THREAD

**Issue by Byroni** [Bananapen/Adv-Game-Design#47]
The blocks seem fine at first, but it doesn't take into consideration force from different angles.

Say there was one block lying on the floor. 

![screen shot 2017-01-22 at 11 49 35 pm](https://cloud.githubusercontent.com/assets/17802259/22191901/7edc30da-e0fd11

If you shoot the right side of the block, you would expect it to spin counter clockwise while moving forward. This isn't what happens though. It instead flies forward straight as if it was shot at perfectly in the middle. 

![screen shot 2017-01-22 at 11 49 35 pm](https://cloud.githubusercontent.com/assets/17802259/22191965/e41c7216-e0fd-11e6-8dad-a943b7f8004e.png)

**Comment by Byroni** [comment]
Ok the images don't work, ill fix that later, unless if yall get what I'm saying.

**Comment by LupinWonse** [comment]
I have determined the Collision Detection mode to be the culprit here, after a lot of testing. I think Continuous and Continuous Dynamic are both buggy at the moment. Things work as expected with Discreet. By slowing down the arrows while increasing their mass we can simply use discreet. If necessary we should look into increasing physics timesteps and/or fixing the Collision Detection method.
